### ISSUE TITLE
Better handle videos with a scheduled video public time (aka Unavailable videos)

### ISSUE THREAD

**Issue by j0nathan-ll0yd** [j0nathan-ll0yd/aws-cloudformation-media-downloader#3]
## 🎯 Self-Healing Workflows: Intelligent Content Availability Detection

This isn't just "handling scheduled videos" - it's **transforming from brittle fail-fast to resilient self-healing workflows** that deliver excellent user experience while eliminating operational noise.

### What Happens Today

**User Journey** (Broken):
1. YouTube creator schedules video for Friday 6pm
2. Feedly RSS publishes URL Thursday (24 hours early)
3. Our pipeline tries to download immediately → FAILS
4. File marked `status: 'failed'` **permanently**
5. GitHub issue created for "Video is unavailable" ($0 value, just noise)
6. iOS app shows "Failed" to user forever
7. Video becomes available Friday 6pm
8. **System never retries** → User never gets video ❌

**User must**:
- Notice video failed
- Contact support OR manually trigger retry
- Wait for manual intervention

**This is a TERRIBLE user experience for a completely solvable problem.**

### The Core Issue: Temporal Availability

**Current Assumption**: All URLs are immediately downloadable (FALSE)

**Reality**: Content has temporal availability:
- **Scheduled videos** → Available at `release_timestamp`
- **Livestreams** → Available when stream starts
- **Premieres** → Available at premiere time
- **Private → Public** → Available when creator changes visibility
- **Geo-unblocked** → Available when region restrictions lift

**We treat temporal unavailability as permanent failure** ← This is the bug.

### What We're Building

**User Journey** (Excellent):
1. YouTube creator schedules video for Friday 6pm
2. Feedly RSS publishes URL Thursday (24 hours early)
3. Our pipeline tries to download → yt-dlp returns `release_timestamp: Friday 6pm`
4. System detects: "Scheduled, not failed"
5. File marked `status: 'scheduled'` with `retryAfter: Friday 6:05pm` (+5 min buffer)
6. **Zero GitHub issue created** (expected delay, not error)
7. iOS app shows "Scheduled for Friday 6pm" (clear user expectation)
8. Friday 6:05pm: System automatically retries
9. Download succeeds → User gets notification "Your video is ready!"
10. **User doesn't even know there was a delay** ✅

**User experience**: **Seamless, delightful, zero intervention required**

### 1. Intelligent Error Classification

**Not All Errors Are Equal**

| Error Type | Current Handling | Intelligent Handling | Outcome |
|-----------|-----------------|---------------------|---------|
| **Scheduled video** | Permanent failure ❌ | Retry at `release_timestamp` | Downloads when available ✅ |
| **Livestream** | Permanent failure ❌ | Retry when stream starts | Captures livestream ✅ |
| **Deleted video** | Permanent failure ✅ | Permanent failure ✅ | GitHub issue (actionable) ✅ |
| **Geo-blocked** | Permanent failure ✅ | Permanent failure ✅ | GitHub issue (actionable) ✅ |
| **Network error** | Permanent failure ❌ | Exponential backoff retry | Recovers from transient failures ✅ |
| **Cookie expired** | Permanent failure ⚠️ | Alert + cookie refresh | Automated remediation ✅ |

**Error Classifier** (`src/util/video-error-classifier.ts`):
```typescript
export function classifyVideoError(
  error: Error,
  videoInfo?: Partial<YtDlpVideoInfo>
): VideoErrorClassification {
  // Case 1: Scheduled video (GODLIKE: retry at exact publish time)
  if (videoInfo?.release_timestamp && videoInfo.release_timestamp > Date.now() / 1000) {
    return {
      category: 'scheduled',
      retryable: true,
      retryAfter: videoInfo.release_timestamp + 300, // +5 min buffer
      reason: `Scheduled for ${new Date(videoInfo.release_timestamp * 1000).toISOString()}`
    }
  }

  // Case 2: Livestream not started (retry periodically)
  if (videoInfo?.is_live === false && videoInfo?.live_status === 'upcoming') {
    return {
      category: 'livestream_upcoming',
      retryable: true,
      retryAfter: videoInfo.release_timestamp || calculateExponentialBackoff(0),
      reason: 'Livestream not yet started'
    }
  }

  // Case 3: Network/transient error (exponential backoff)
  if (isNetworkError(error)) {
    return {
      category: 'transient',
      retryable: true,
      retryAfter: calculateExponentialBackoff(retryCount),
      reason: 'Transient network error'
    }
  }

  // Case 4: Permanent failure (geo-block, deleted, private)
  return {
    category: 'permanent',
    retryable: false,
    reason: error.message
  }
}
```

**Result**: Zero false failures, precise retry timing, excellent UX

### 2. DynamoDB as Scheduler (Zero External Dependencies)

**Current Retry Approaches** (Complex):
- ❌ AWS EventBridge scheduled rules (one rule per video, quota limits)
- ❌ SQS delayed messages (15-minute max delay)
- ❌ Step Functions wait states (expensive, complex)
- ❌ Lambda scheduled cron (scans entire table, inefficient)

**GODLIKE Approach**: DynamoDB + GSI + Lambda Scan

**Schema Enhancement**:
```typescript
// src/entities/Files.ts (ElectroDB entity)
export const Files = new Entity({
  attributes: {
    fileId: {type: 'string', required: true},
    status: {type: 'string', required: true}, // Add: 'scheduled'
    retryAfter: {type: 'number'},            // NEW: Unix timestamp
    retryCount: {type: 'number', default: 0}, // NEW: Attempt counter
    scheduledPublishTime: {type: 'number'},   // NEW: Original publish time
    lastError: {type: 'string'}               // NEW: Last error message
  },
  indexes: {
    byStatus: {
      index: 'gsi1',
      pk: {field: 'GSI1PK', composite: ['status']},
      sk: {field: 'GSI1SK', composite: ['retryAfter']} // Sort by retry time!
    }
  }
})
```

**Retry Lambda** (Scheduled Hourly):
```typescript
// src/lambdas/RetryScheduledFiles/src/index.ts

export const handler = withXRay(async (event, context) => {
  const now = Math.floor(Date.now() / 1000)

  // Query GSI for scheduled files ready to retry
  const {data: scheduledFiles} = await Files.query.byStatus({
    status: 'scheduled'
  }).where(
    ({retryAfter}, {lte}) => lte(retryAfter, now)
  ).go()

  logInfo(`Found ${scheduledFiles.length} files ready for retry`)

  // Process retries (with concurrency limit)
  await Promise.all(
    scheduledFiles.map(file =>
      Lambda.invoke({
        FunctionName: 'StartFileUpload',
        InvocationType: 'Event', // Async
        Payload: JSON.stringify({fileId: file.fileId})
      })
    )
  )

  return {processed: scheduledFiles.length}
})
```

**EventBridge Schedule**:
```hcl
# terraform/retry_scheduled_files.tf

resource "aws_cloudwatch_event_rule" "RetryScheduledFiles" {
  name                = "RetryScheduledFiles"
  schedule_expression = "rate(1 hour)"  # Check hourly
  state               = "ENABLED"
}

resource "aws_cloudwatch_event_target" "RetryScheduledFiles" {
  rule = aws_cloudwatch_event_rule.RetryScheduledFiles.name
  arn  = aws_lambda_function.RetryScheduledFiles.arn
}
```

**Benefits**:
- ✅ **Zero external dependencies** (DynamoDB + Lambda only)
- ✅ **Efficient** (GSI sorts by `retryAfter`, only scan overdue files)
- ✅ **Scalable** (handles millions of scheduled files)
- ✅ **Cost-effective** ($0.00001 per retry check)
- ✅ **Simple** (60 lines of code)

### 3. Operational Excellence: Zero Noise

**Current GitHub Issues** (Noise):
```
Issue #234: "Video is unavailable" (scheduled video, expected)
Issue #235: "Video is unavailable" (scheduled video, expected)
Issue #236: "Video is unavailable" (scheduled video, expected)
Issue #237: "Video is unavailable" (network blip, transient)
Issue #238: "Video is unavailable" (ACTUAL problem: geo-blocked)
```

**Signal-to-Noise Ratio**: 1:5 (only #238 is actionable)

**With Intelligent Classification**:
```typescript
// Only create GitHub issues for PERMANENT failures
if (classification.category === 'permanent') {
  await createGitHubIssue({
    title: `Failed to download video: ${fileId}`,
    body: `Reason: ${classification.reason}`
  })
}

// For retryable errors: Just log + schedule retry
if (classification.retryable) {
  logInfo(`Scheduling retry for ${fileId}`, {
    retryAfter: new Date(classification.retryAfter * 1000).toISOString(),
    reason: classification.reason
  })
}
```

**Result GitHub Issues**:
```
Issue #234: "Failed to download video: Geo-blocked in current region" (ACTIONABLE)
```

**Signal-to-Noise Ratio**: 1:1 (100% actionable) ✅

### 4. Pattern for Future Content Types

**This Architecture Handles**:

- ✅ **Scheduled videos** → Retry at `release_timestamp`
- ✅ **Livestreams** → Retry when stream starts
- ✅ **Premieres** → Retry at premiere time
- ✅ **Private → Public transitions** → Retry with exponential backoff
- ✅ **Geo-restrictions lift** → Retry periodically (if we add VPN rotation)
- ✅ **Network transient errors** → Retry with backoff
- ✅ **Cookie expiration** → Alert + automated cookie refresh

**Future Expansion**:
```typescript
// src/util/video-error-classifier.ts

// NEW: Livestream handling
if (videoInfo?.is_live === false && videoInfo?.live_status === 'upcoming') {
  return {
    category: 'livestream_upcoming',
    retryable: true,
    retryAfter: videoInfo.release_timestamp || now + 3600,
    reason: 'Livestream scheduled'
  }
}

// NEW: Premiere handling
if (videoInfo?.premiere_timestamp) {
  return {
    category: 'premiere',
    retryable: true,
    retryAfter: videoInfo.premiere_timestamp + 60,
    reason: 'Premiere scheduled'
  }
}
```

**Extensible for ANY temporal availability pattern**

### 5. User Experience: Transparent Status

**iOS App Status Updates**:
```swift
// iOS app shows status based on DynamoDB record

switch file.status {
case .pending:
    "Queued for download"
case .processing:
    "Downloading... \(progress)%"
case .scheduled:
    if let publishTime = file.scheduledPublishTime {
        "Scheduled for \(formatDate(publishTime))"
    } else {
        "Scheduled (retrying soon)"
    }
case .completed:
    "Ready to watch"
case .failed:
    "Failed: \(file.lastError ?? 'Unknown error')"
}
```

**User sees**:
- ❌ Before: "Failed" (confusing, feels broken)
- ✅ After: "Scheduled for Friday 6:00 PM" (clear expectation)

**Result**: User trusts the system, zero support tickets

### Phase 1: Error Classification (4-6 hours)
- [ ] Create `src/util/video-error-classifier.ts`
- [ ] Implement `classifyVideoError()` with all error types
- [ ] Implement `calculateExponentialBackoff()`
- [ ] Write unit tests (all error cases covered)
- [ ] **Deliverable**: Error classifier with 100% test coverage

### Phase 2: DynamoDB Schema Enhancement (2-3 hours)
- [ ] Update Files ElectroDB entity (add `retryAfter`, `retryCount`, etc.)
- [ ] Update GSI to sort by `retryAfter` (already have gsi1)
- [ ] Add `FileStatus.Scheduled` enum value
- [ ] Migrate existing `failed` records (backfill data)
- [ ] **Deliverable**: Schema supports retry metadata

### Phase 3: StartFileUpload Error Handling (4-6 hours)
- [ ] Update StartFileUpload to use error classifier
- [ ] Handle retryable errors: Update DynamoDB with retry metadata
- [ ] Handle permanent errors: Create GitHub issues (existing logic)
- [ ] Attempt metadata fetch for unavailable videos (`yt-dlp --skip-download`)
- [ ] Add CloudWatch metrics (`ScheduledVideoDetected`, `RetryScheduled`)
- [ ] **Deliverable**: Intelligent error handling in StartFileUpload

### Phase 4: Retry Lambda (4-6 hours)
- [ ] Create `src/lambdas/RetryScheduledFiles/`
- [ ] Implement hourly scan of `status: 'scheduled'` with `retryAfter <= now`
- [ ] Invoke StartFileUpload for each overdue retry
- [ ] Add concurrency limiting (don't overwhelm yt-dlp)
- [ ] Add retry exhaustion handling (max retries exceeded → `failed`)
- [ ] **Deliverable**: Automated retry Lambda

### Phase 5: Infrastructure + Testing (4-6 hours)
- [ ] Create `terraform/retry_scheduled_files.tf`
- [ ] Deploy EventBridge hourly schedule
- [ ] Write integration test (schedule video → retry → download)
- [ ] Test with real scheduled video (YouTube test channel)
- [ ] Monitor for 1 week, tune retry timing/backoff
- [ ] **Deliverable**: Production-ready self-healing workflow

**Total: 2-3 days (18-27 hours)**

### User Experience
- [ ] **100% success rate** for scheduled videos (eventually download when available)
- [ ] **Zero manual intervention** required (fully automated)
- [ ] **Clear status communication** (iOS app shows "Scheduled for..." not "Failed")
- [ ] **Zero support tickets** for scheduled video "failures"

### Operational Excellence
- [ ] **Zero GitHub issues** for scheduled videos (no noise)
- [ ] **100% actionable GitHub issues** (only permanent failures reported)
- [ ] **Average retry latency ≤1 hour** after video becomes available
- [ ] **Retry success rate ≥95%** (retries work correctly)

### System Health
- [ ] **CloudWatch metrics** track scheduled video detection rate
- [ ] **CloudWatch alarms** alert on retry exhaustion (potential bugs)
- [ ] **Retry queue size** monitored (detect backlog)

### Investment
- **2-3 days development** ($2,400-$3,600 equivalent)
- **$0.10/month infrastructure** (RetryScheduledFiles Lambda invocations)

### Returns

**Year 1 User Experience**:
- **Support ticket reduction**: 5 tickets/month × 15 min × 12 = 15 hours saved ($2,250)
- **User trust**: Zero "broken" failures → Higher retention (unquantified)
- **Feature completeness**: Actually download ALL videos user wants (priceless)

**Year 1 Operational**:
- **GitHub issue noise reduction**: 10 issues/month → 2 issues/month = 80% reduction
- **Triage time saved**: 8 issues/month × 5 min × 12 = 8 hours saved ($1,200)

**Year 1 Total Tangible**: $3,450 saved  
**Payback Period**: ~1 month

**Years 2-5**:
- **Ongoing savings**: $3,450/year × 4 = $13,800
- **Pattern reuse**: Handles livestreams, premieres, future content types
- **User delight**: Seamless experience = higher lifetime value

## Why This Is GODLIKE

This isn't "handling scheduled videos" - it's **self-healing production resilience**.

**We transform**:
- ❌ Brittle fail-fast → ✅ Resilient self-healing
- ❌ Temporal unavailability = permanent failure → ✅ Intelligent retry at exact availability time
- ❌ User sees "Failed" forever → ✅ User sees "Scheduled for Friday 6pm"
- ❌ GitHub issue noise → ✅ 100% actionable alerts
- ❌ Manual intervention required → ✅ Fully automated

**We unlock**:
- ✅ **Excellent user experience** → Videos download when available, zero intervention
- ✅ **Operational excellence** → Zero noise, 100% actionable issues
- ✅ **Extensible pattern** → Handles livestreams, premieres, any temporal content
- ✅ **DynamoDB as scheduler** → Zero external dependencies
- ✅ **Self-healing workflows** → Production resilience at its finest

## Recommendation

**HIGH PRIORITY** - User experience and operational excellence.

**Next Steps**:
1. **Phase 1 (4-6 hours)**: Error classifier implementation
2. **Phase 2 (2-3 hours)**: DynamoDB schema enhancement
3. **Phase 3 (4-6 hours)**: StartFileUpload intelligent error handling
4. **Phase 4 (4-6 hours)**: RetryScheduledFiles Lambda
5. **Phase 5 (4-6 hours)**: Infrastructure + testing

**This transforms user experience from frustrating failures to seamless, delightful automation.**

## References

- **YouTube Scheduled Videos**: https://support.google.com/youtube/answer/1270709
- **yt-dlp Metadata Extraction**: https://github.com/yt-dlp/yt-dlp#output-template
- **ElectroDB Query Patterns**: https://electrodb.dev/en/queries/
- **CloudWatch Events Scheduling**: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html

**This is production-grade self-healing infrastructure that users don't even know is there - because it just works.**
